extraction:
  output-format: "sdf"
  hbond-min-distance: 1.6
  hbond-max-distance: 2.5
  exclude-imines: false
  hbond-atoms:
   - 7
   - 8
aggregation:
  resolution: 10000
  # Can be scf_energy, free_energy, net_charge
  label-name: "free_energy"
  atom-types:
    - 1
    - 6
    - 7
    - 8
  amine-types:
    - 1
    - 2
    - 3
  feature-types:
    - "bonds"
    - "angles"
    - "dihedrals"
    - "hbonds"
  plotting:
    save-dir: "./figure-test"
