extraction:
  output-format: "sdf"
  hbond-min-distance: 1.6
  hbond-max-distance: 2.5
  exclude-imines: false
  hbond-atoms:
   - 7
   - 8
aggregation:
  kde-bandwidth: 0.3
  resolution: 1000
  label-name: "scf_energy"
  atom-types:
    - 1
    - 6
    - 7
    - 8
  amine-types:
    - 1
    - 2
    - 3
  feature-types:
    - "bonds"
    - "angles"
    - "dihedrals"
    - "hbonds"
