extraction:
  # Filter configuration
  output-format: "sdf"
  bond-min-distance: 0
  bond-max-distance:  100 # Practically infinite; why constrain bond length?
  min-heavy-atoms: 1
  max-heavy-atoms: 8

  # Configuration when extracting mol info
  hbond-atoms:
   - 7
   - 8
  hbond-min-distance: 1.6
  hbond-max-distance: 2.5
  substructures:  # List of SMARTS strings to search the structure for

aggregation:
  # Histogram creation configuration
  resolution: 10000
  bond-bandwidth: 0.07  # scott, sliverman, float or none
  angle-bandwidth: 0.07  # scott, sliverman, float or none
  use-minmax: true
  weighted-bins: false

  # Feature creation config
  atom-types:
    - 1
    - 6
    - 7
    - 8
  amine-types:
    - 1
    - 2
    - 3
  feature-types:
    - "bonds"
    - "angles"
    - "dihedrals"
    - "hbonds"

plotting:
  save-dir: "./data/qm9/figures/bw0.07unfiltered"
  show-dist: true
  show-kde: true
  plot-style: "whitegrid"
